### ISSUE TITLE
broken example test

### ISSUE THREAD

**Issue by bskydive** [KevinGrandon/ghostjs#109]
After running your example:

```
import ghost from 'ghostjs'
import assert from 'assert'
 
describe('Google', () => {
  it('has a title', async () => {
    await ghost.open('http://google.com')
    let pageTitle = await ghost.pageTitle()
    assert.equal(pageTitle, 'Google')
 
    // Get the content of the body 
    let body = await ghost.findElement('body')
    console.log(await body.html())
    assert.isTrue(await body.isVisible())
 
    // Wait for an element and click it 
    let footerLink = await ghost.waitForElement('footer a')
    footerLink.click()
  })
})

```

always appears:

```
1 failing

  1) Google has a title:
     TypeError: Cannot read property 'call' of undefined
      at _callee$ (ex1.js:5:21)
      at tryCatch (node_modules/regenerator-runtime/runtime.js:62:40)
      at GeneratorFunctionPrototype.invoke [as _invoke] (node_modules/regenerator-runtime/runtime.js:336:22)
      at GeneratorFunctionPrototype.prototype.(anonymous function) [as next] (node_modules/regenerator-runtime/runtime.js:95:21)
      at step (ex1.js:2:1)
      at ex1.js:2:1
      at run (node_modules/core-js/modules/es6.promise.js:87:22)
      at node_modules/core-js/modules/es6.promise.js:100:28
      at flush (node_modules/core-js/modules/_microtask.js:18:9)

```

**Comment by KevinGrandon** [comment]
Thank you for filing this! Turned out to just be a problem with one of the assertion calls. I'll update the example to get it working again. Please let me know if you run into any other issues.
