### ISSUE TITLE
resolve symlink before spawning google-chrome

### ISSUE THREAD

**Issue by ALangguth** [KevinGrandon/ghostjs#171]
My system:
- ubuntu 16.0.4.5 LTS
- node: v8.11.2

When I try to run this library with google-chrome I get the following error:
```
/usr/bin/google-chrome
Error executing Chrome at /usr/bin/google-chrome

Error: spawn /usr/bin/google-chrome
 ENOENT
    at _errnoException (util.js:992:11)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:190:19)
    at onErrorNT (internal/child_process.js:372:16)
    at _combinedTickCallback (internal/process/next_tick.js:138:11)
    at process._tickCallback (internal/process/next_tick.js:180:9)
    at Function.Module.runMain (module.js:695:11)
    at startup (bootstrap_node.js:191:16)
    at bootstrap_node.js:612:3
CDP Error: Error: connect ECONNREFUSED 127.0.0.1:9222
    at Object._errnoException (util.js:992:11)
    at _exceptionWithHostPort (util.js:1014:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1186:14)
```

`/usr/bin/google-chrome` is actually just a symlink on my system.
It is a compltete symlink-chain:
/usr/bin/google-chrome -> /etc/alternatives/google-chrome -> /usr/bin/google-chrome-stable -> /opt/google/chrome/google-chrome

If I set the `CHROME_BIN` env-variable to `/etc/alternatives/google-chrome`, or anything else in the chain, everything is working fine.

I suggest adding a simple `fs.realpathSync()` call to the binary.getPath()-function like so:
```
const getPath = () => {
	if (process.platform === 'darwin') {
	  return '/Applications/Google\ Chrome\ Canary.app/Contents/MacOS/Google\ Chrome\ Canary'
  } else {
	  return fs.realpathSync(shell.exec('which google-chrome').stdout)
  }
}
```

**Comment by KevinGrandon** [comment]
Thank you very much for the very detailed bug and suggested fix. I'm currently recommending that folks use puppeteer, though if folks are still finding this useful, happy to help maintain for now.

I'll open up a PR and publish the fix.
